export const OFFICE_CODES = [
  "MID-0001 | National Office",
  "MID-0002 | Regional Office I",
  "MID-0003 | Regional Office II",
  "MID-0004 | Regional Office III",
  "MID-0005 | Regional Office IV-A",
  "MID-0006 | Regional Office IV-B",
  "MID-0007 | Regional Office V",
  "MID-0008 | Regional Office VI",
  "MID-0009 | Regional Office VII",
  "MID-0010 | Regional Office VIII",
  "MID-0011 | Regional Office IX",
  "MID-0012 | Regional Office X",
  "MID-0013 | Regional Office XI",
  "MID-0014 | Regional Office XII",
  "MID-0015 | Regional Office CAR",
  "MID-0016 | Regional Office CARAGA",
  "MID-0017 | Regional Office BARMM",
  "MID-0018 | Monitoring and Evaluation Office",
  "MID-0019 | Licensing and Registration Office",
  "MID-0020 | Legal Services Office",
  "MID-0021 | Finance Office",
  "MID-0022 | Central Support Office",
  "MID-0023 | IT Services Office",
  "MID-0024 | HR and Administration Office",
  "MID-0025 | External Affairs Office",
  "MID-0026 | Records and Archives Office",
  "MID-0027 | Planning Office",
  "MID-0028 | Policy and Standards Office",
  "MID-0029 | Field Operations Office",
  "MID-0030 | Audit and Compliance Office",
  // Add the remaining office codes here to complete the full list of 200+ codes
];
